# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmAddRegistro.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmRegistro(object):
    def setupUi(self, FrmRegistro):
        FrmRegistro.setObjectName("FrmRegistro")
        FrmRegistro.resize(630, 577)
        FrmRegistro.setFixedSize(630, 577)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/btnAdicionarRegistro.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmRegistro.setWindowIcon(icon)
        FrmRegistro.setAutoFillBackground(False)
        FrmRegistro.setStyleSheet("border-top-color: rgb(135, 181, 255);\n""")

        self.centralwidget = QtWidgets.QWidget(FrmRegistro)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.TopFrame = QtWidgets.QFrame(self.centralwidget)
        self.TopFrame.setGeometry(QtCore.QRect(50, 20, 541, 401))
        self.TopFrame.setSizeIncrement(QtCore.QSize(10, 10))
        self.TopFrame.setBaseSize(QtCore.QSize(10, 10))
        self.TopFrame.setAutoFillBackground(False)
        self.TopFrame.setStyleSheet("")
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.layoutWidget = QtWidgets.QWidget(self.TopFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 241, 377))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.lineEditPatri = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditPatri.setObjectName("lineEditPatri")
        self.gridLayout.addWidget(self.lineEditPatri, 14, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.labelMod = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelMod.setFont(font)
        self.labelMod.setObjectName("labelMod")
        self.gridLayout.addWidget(self.labelMod, 10, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(13, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.lineEditNSer = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditNSer.setObjectName("lineEditNSer")
        self.gridLayout.addWidget(self.lineEditNSer, 17, 0, 1, 1)
        self.labelNSerie = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelNSerie.setFont(font)
        self.labelNSerie.setObjectName("labelNSerie")
        self.gridLayout.addWidget(self.labelNSerie, 16, 0, 1, 1)
        self.lineEditMod = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditMod.setObjectName("lineEditMod")
        self.gridLayout.addWidget(self.lineEditMod, 11, 0, 1, 1)
        self.labelLab = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelLab.setFont(font)
        self.labelLab.setObjectName("labelLab")
        self.gridLayout.addWidget(self.labelLab, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 0, 1, 1)
        self.labelPatri = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPatri.setFont(font)
        self.labelPatri.setObjectName("labelPatri")
        self.gridLayout.addWidget(self.labelPatri, 13, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 15, 0, 1, 1)
        self.lineEditFab = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFab.setObjectName("lineEditFab")
        self.gridLayout.addWidget(self.lineEditFab, 8, 0, 1, 1)
        self.labelFab = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelFab.setFont(font)
        self.labelFab.setObjectName("labelFab")
        self.gridLayout.addWidget(self.labelFab, 7, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 12, 0, 1, 1)
        self.lineEditLab = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditLab.setObjectName("lineEditLab")
        self.gridLayout.addWidget(self.lineEditLab, 2, 0, 1, 1)
        self.labelPad = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPad.setFont(font)
        self.labelPad.setObjectName("labelPad")
        self.gridLayout.addWidget(self.labelPad, 4, 0, 1, 1)
        self.lineEditFab_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFab_2.setObjectName("lineEditFab_2")
        self.gridLayout.addWidget(self.lineEditFab_2, 5, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.TopFrame)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 521, 401))
        self.groupBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(330, 10, 158, 311))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(13, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 0, 0, 1, 1)
        self.labelDCali = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDCali.setFont(font)
        self.labelDCali.setObjectName("labelDCali")
        self.gridLayout_2.addWidget(self.labelDCali, 1, 0, 1, 1)
        self.dateEditCali = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEditCali.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEditCali.setObjectName("dateEditCali")
        self.gridLayout_2.addWidget(self.dateEditCali, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 3, 0, 1, 1)
        self.labelDChec = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDChec.setFont(font)
        self.labelDChec.setObjectName("labelDChec")
        self.gridLayout_2.addWidget(self.labelDChec, 4, 0, 1, 1)
        self.dateEditChec = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEditChec.setObjectName("dateEditChec")
        self.gridLayout_2.addWidget(self.dateEditChec, 5, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem8, 6, 0, 1, 1)
        self.labelDVenc = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDVenc.setFont(font)
        self.labelDVenc.setObjectName("labelDVenc")
        self.gridLayout_2.addWidget(self.labelDVenc, 7, 0, 1, 1)
        self.dateEditVenc = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEditVenc.setObjectName("dateEditVenc")
        self.gridLayout_2.addWidget(self.dateEditVenc, 8, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 9, 0, 1, 1)
        self.labelDProCali = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDProCali.setFont(font)
        self.labelDProCali.setObjectName("labelDProCali")
        self.gridLayout_2.addWidget(self.labelDProCali, 10, 0, 1, 1)
        self.dateEditProxCali = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEditProxCali.setObjectName("dateEditProxCali")
        self.gridLayout_2.addWidget(self.dateEditProxCali, 11, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 12, 0, 1, 1)
        self.labelDSaida = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelDSaida.setFont(font)
        self.labelDSaida.setObjectName("labelDSaida")
        self.gridLayout_2.addWidget(self.labelDSaida, 13, 0, 1, 1)
        self.dateEditSaida = QtWidgets.QDateEdit(self.layoutWidget1)
        self.dateEditSaida.setObjectName("dateEditSaida")
        self.gridLayout_2.addWidget(self.dateEditSaida, 14, 0, 1, 1)
        self.groupBox.raise_()
        self.layoutWidget.raise_()
        self.DownFrame = QtWidgets.QFrame(self.centralwidget)
        self.DownFrame.setGeometry(QtCore.QRect(49, 429, 541, 101))
        self.DownFrame.setAutoFillBackground(False)
        self.DownFrame.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.DownFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DownFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DownFrame.setObjectName("DownFrame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.DownFrame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 521, 81))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.groupBox_2.setBaseSize(QtCore.QSize(0, 0))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnSalvar = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSalvar.setGeometry(QtCore.QRect(420, 10, 91, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalvar.setFont(font)
        self.btnSalvar.setAutoFillBackground(False)
        self.btnSalvar.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon1)
        self.btnSalvar.setIconSize(QtCore.QSize(26, 40))
        self.btnSalvar.setObjectName("btnSalvar")
        self.DownFrame.raise_()
        self.TopFrame.raise_()
        FrmRegistro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FrmRegistro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menubar.setObjectName("menubar")
        FrmRegistro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FrmRegistro)
        self.statusbar.setObjectName("statusbar")
        FrmRegistro.setStatusBar(self.statusbar)

        self.retranslateUi(FrmRegistro)
        QtCore.QMetaObject.connectSlotsByName(FrmRegistro)

    def retranslateUi(self, FrmRegistro):
        _translate = QtCore.QCoreApplication.translate
        FrmRegistro.setWindowTitle(_translate("FrmRegistro", "Adicionar Registro"))
        self.labelMod.setText(_translate("FrmRegistro", "Modelo"))
        self.labelNSerie.setText(_translate("FrmRegistro", "Número de Série"))
        self.labelLab.setText(_translate("FrmRegistro", "Labortório"))
        self.labelPatri.setText(_translate("FrmRegistro", "Patrimônio"))
        self.labelFab.setText(_translate("FrmRegistro", "Fabricante"))
        self.labelPad.setText(_translate("FrmRegistro", "Padrão"))
        self.labelDCali.setText(_translate("FrmRegistro", "Data de Calibração"))
        self.labelDChec.setText(_translate("FrmRegistro", "Data de Checagem"))
        self.labelDVenc.setText(_translate("FrmRegistro", "Data de Vencimento"))
        self.labelDProCali.setText(_translate("FrmRegistro", "Data da Próxima Calibração"))
        self.labelDSaida.setText(_translate("FrmRegistro", "Data de Saída"))
        self.btnSalvar.setText(_translate("FrmRegistro", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmRegistro = QtWidgets.QMainWindow()
    ui = Ui_FrmRegistro()
    ui.setupUi(FrmRegistro)
    FrmRegistro.show()
    sys.exit(app.exec_())
